// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TownManager.Infrastructure.Persistence;

#nullable disable

namespace TownManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720135952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BotPersonality")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.BuildOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BuildingType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("BuildOrders");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.TrainOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("Completed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("TimePerUnit")
                        .HasColumnType("interval");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("TrainOrders");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.TroopMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetVillageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TargetCoordinates", "TownManager.Domain.Entities.Villages.TroopMovement.TargetCoordinates#Coordinates", b1 =>
                        {
                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("TargetMapX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("TargetMapY");
                        });

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("TroopMovements");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAttackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastTickAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VillageType")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Coordinates", "TownManager.Domain.Entities.Villages.Village.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("MapX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("MapY");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("TownManager.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TownManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TownManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TownManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TownManager.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Report", b =>
                {
                    b.HasOne("TownManager.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.BuildOrder", b =>
                {
                    b.HasOne("TownManager.Domain.Entities.Villages.Village", "Village")
                        .WithMany("BuildOrders")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.Building", b =>
                {
                    b.HasOne("TownManager.Domain.Entities.Villages.Village", null)
                        .WithMany("Buildings")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.TrainOrder", b =>
                {
                    b.HasOne("TownManager.Domain.Entities.Villages.Village", "Village")
                        .WithMany("TrainOrders")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.TroopMovement", b =>
                {
                    b.HasOne("TownManager.Domain.Entities.Villages.Village", "Village")
                        .WithMany("TroopMovements")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TownManager.Domain.Entities.Resources", "CarriedResources", b1 =>
                        {
                            b1.Property<Guid>("TroopMovementId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Beer")
                                .HasColumnType("double precision");

                            b1.Property<double>("Clay")
                                .HasColumnType("double precision");

                            b1.Property<double>("Iron")
                                .HasColumnType("double precision");

                            b1.Property<double>("Wood")
                                .HasColumnType("double precision");

                            b1.HasKey("TroopMovementId");

                            b1.ToTable("TroopMovements");

                            b1.WithOwner()
                                .HasForeignKey("TroopMovementId");
                        });

                    b.OwnsOne("TownManager.Domain.Entities.Troops", "Troops", b1 =>
                        {
                            b1.Property<Guid>("TroopMovementId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Counts")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.HasKey("TroopMovementId");

                            b1.ToTable("TroopMovements");

                            b1.WithOwner()
                                .HasForeignKey("TroopMovementId");
                        });

                    b.Navigation("CarriedResources");

                    b.Navigation("Troops")
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.Village", b =>
                {
                    b.HasOne("TownManager.Domain.Entities.Player", "Player")
                        .WithMany("Villages")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TownManager.Domain.Entities.Resources", "Resources", b1 =>
                        {
                            b1.Property<Guid>("VillageId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Beer")
                                .HasColumnType("double precision")
                                .HasColumnName("Beer");

                            b1.Property<double>("Clay")
                                .HasColumnType("double precision")
                                .HasColumnName("Clay");

                            b1.Property<double>("Iron")
                                .HasColumnType("double precision")
                                .HasColumnName("Iron");

                            b1.Property<double>("Wood")
                                .HasColumnType("double precision")
                                .HasColumnName("Wood");

                            b1.HasKey("VillageId");

                            b1.ToTable("Villages");

                            b1.WithOwner()
                                .HasForeignKey("VillageId");
                        });

                    b.OwnsOne("TownManager.Domain.Entities.Troops", "Troops", b1 =>
                        {
                            b1.Property<Guid>("VillageId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Counts")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.HasKey("VillageId");

                            b1.ToTable("Villages");

                            b1.WithOwner()
                                .HasForeignKey("VillageId");
                        });

                    b.Navigation("Player");

                    b.Navigation("Resources")
                        .IsRequired();

                    b.Navigation("Troops")
                        .IsRequired();
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Player", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("TownManager.Domain.Entities.Villages.Village", b =>
                {
                    b.Navigation("BuildOrders");

                    b.Navigation("Buildings");

                    b.Navigation("TrainOrders");

                    b.Navigation("TroopMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
